"""One hundred labeled prompts for the Smart router. Labels are the tier a careful admin would pick."""

ECONOMY = [
    "Translate 'good morning' to French.",
    "Classify this review as positive or negative: 'Loved it, would buy again.'",
    "Extract the invoice number from: INV-2291 due 3 April.",
    "What is the capital of Peru?",
    "Define amortization in one sentence.",
    "Rewrite this in a friendlier tone: Pay the balance now.",
    "Fix grammar: she go to office yesterday.",
    "Convert 5 miles to kilometres.",
    "Format this as JSON: name Bob, age 34, city Lima.",
    "Sentiment of: the food was cold and the waiter was rude.",
    "Spell check: recieve, definately, seperate.",
    "Uppercase this: quarterly results.",
    "Shorten to ten words: our team will be attending the conference in Berlin next week to present.",
    "TL;DR: the meeting moved to Friday because two people are travelling.",
    "List three synonyms for fast.",
    "Give me 3 names for a company cat.",
    "How do you say thank you in Japanese?",
    "What day of the week is 1 January 2027?",
    "Abbreviate Department of Finance and Administration.",
    "One word for very happy.",
    "Is 17 a prime number? Yes or no.",
    "True or false: Paris is in Spain.",
    "Tag this ticket: printer on floor 3 not working.",
    "Categorize this request: refund for duplicate charge.",
    "Lowercase THIS SENTENCE PLEASE.",
    "Antonym of cheap.",
    "Convert 3pm Eastern to GMT.",
    "Define EBITDA.",
    "Rewrite for a fifth grader: photosynthesis converts light into chemical energy.",
    "Proofread: Their going to the meting at 3.",
    "Extract emails from: contact bob@example.com and amy@example.org today.",
    "One sentence summary: the vendor confirmed delivery for the 12th.",
    "Classify the intent: I want to cancel my subscription.",
    "Hi there",
]

WORKHORSE = [
    "Write a polite email to a supplier asking for an updated delivery date for order 4471, and mention we need it before month end.",
    "Summarize the key points of our quarterly sales meeting for the leadership newsletter, keeping it under 150 words.",
    "Draft a job posting for a junior accountant in the finance team, including responsibilities and required experience.",
    "Write a Python function that reads a CSV file and returns the mean of a named column, with a docstring.",
    "Explain what an API is to a new business user who has never written code.",
    "Create a short onboarding checklist for a new hire in the procurement team.",
    "Write a LinkedIn post announcing our new sustainability report, professional but warm.",
    "Turn these bullet points into a paragraph: hired two engineers, shipped mobile app, revenue up 12 percent.",
    "Generate five interview questions for a customer support manager role.",
    "Write a SQL query that returns the top ten customers by total order value in 2025.",
    "Suggest an agenda for a 45 minute project kickoff meeting with a new client.",
    "Explain the difference between gross margin and net margin with a simple example.",
    "Write a thank-you note to a colleague who covered my on-call shift last weekend.",
    "Describe three ways a training team could measure whether a workshop improved skills.",
    "Write a short product description for an ergonomic office chair aimed at remote workers.",
    "Help me phrase feedback for a report that was late and missing the executive summary.",
    "Create a table of monthly milestones for launching an internal newsletter over one quarter.",
    "Write a bash script that backs up a folder to a dated archive every night.",
    "Explain how prompt caching reduces cost when the same system prompt is reused.",
    "Draft a Slack message reminding the team to submit expense reports by Thursday.",
    "What are common causes of invoice matching failures in accounts payable, briefly?",
    "Write a haiku about the end of the fiscal year for the finance newsletter.",
    "Give me a plain-English explanation of what a knowledge base is for an AI assistant.",
    "Create a quiz with five multiple-choice questions about basic data privacy for employees.",
    "Write a JavaScript function that debounces another function by a given delay.",
    "Outline a 20 minute talk introducing the AI playground to a group of new users.",
    "Compose a customer apology email about a delayed shipment, offering a ten percent discount.",
    "Explain what a model's context window means and why it matters for long documents.",
    "Write a short FAQ with four questions about our travel reimbursement policy.",
    "Recommend a weekly study plan for someone learning SQL in a month, one hour per day.",
    "Draft a two-paragraph welcome message for the community showcase page.",
    "Write a regular expression that matches UK postcodes and explain each part briefly.",
    "Summarize this paragraph in three bullet points: our support volume rose in March because of the billing change, most tickets were about duplicate charges, and the fix shipped on the 20th.",
]

PREMIUM = [
    "Design a system architecture for a multi-tenant document processing platform and analyze the trade-offs between queue-based and event-driven ingestion.",
    "Review this contract clause for compliance risks under GDPR and explain the reasoning behind each concern.",
    "Debug why our nightly reconciliation job produces duplicate rows; here is the SQL and the schema, and propose a root cause and fix.",
    "Prove that the algorithm below terminates and derive its worst-case complexity step by step.",
    "Write a comprehensive migration plan to move our on-premises Postgres cluster to Azure with a rollback strategy and risk analysis.",
    "Evaluate three vendor proposals for an identity provider and produce a comparison matrix with a recommendation and rationale.",
    "Research the regulatory requirements for AI use in hiring across the EU and the US and summarize the compliance implications for our HR team.",
    "Refactor this 300-line Python module for readability and performance; analyze the hotspots first and explain each change.",
    "Perform a security review of this authentication flow, produce a threat model, and prioritize the mitigations.",
    "Draft a technical specification for an evaluation harness with golden datasets, rubric scoring, and calibration of an LLM judge.",
    "Analyze our churn data description and propose a strategy to reduce churn, with a forecast of the expected impact under three scenarios.",
    "Critique this product strategy document in depth, identify the weakest assumptions, and suggest experiments to test them.",
    "Compare and contrast LangGraph and the OpenAI Agents SDK for a durable, human-in-the-loop workflow and recommend one with detailed reasoning.",
    "Audit this invoice reconciliation procedure for control gaps and derive a set of compensating controls.",
    "Simulate how a 15 percent tariff would affect our supply chain costs and analyze which suppliers to renegotiate first.",
    "Design a comprehensive data governance strategy for a bank, covering lineage, retention, and regulatory reporting.",
    "Here is a 40-line stack trace and the relevant code; find the root cause and explain why the fix is correct.",
    "Evaluate the trade-offs between fine-tuning and retrieval for our domain assistant and write an implementation plan.",
    "Produce an in-depth research brief on carbon accounting standards and how they affect our supplier contracts.",
    "Why does this distributed cache return stale values under load? Analyze the consistency model and propose a fix.",
    "Write a proposal for migrating our monolith to services, including an architecture diagram description, phasing, and a risk analysis.",
    "Derive the pricing formula for our subscription tiers from the cost model below and analyze the margin sensitivity.",
    "Review this legal memo on data residency and critique its reasoning against the current regulatory guidance.",
    "Optimize this query plan for a 2 billion row fact table and explain the reasoning behind each index recommendation.",
    "Evaluate the audit findings below, derive the root cause of each control failure, and draft the remediation plan.",
    "Analyze the architecture of this event sourcing system and identify the trade-offs of its snapshotting strategy.",
    "Develop a comprehensive compliance strategy for SOX controls automated by AI agents, with a threat model for fabricated evidence.",
    "Research and compare three vector database options for a 50 million document corpus and derive a cost forecast.",
    "Debug this intermittent race condition in the payment service; the logs and code are attached; analyze and propose a fix.",
    "Design a step by step implementation plan for a nightly canary with automatic rollback and analyze its failure modes.",
    "Critique the specification below for an agent evaluation service and propose a stronger rubric with calibrated thresholds.",
    "Evaluate whether we should migrate to a new ERP, analyze the strategy risks, and prepare a recommendation for the board.",
    "Write an in-depth security review of our MCP connector approval workflow and derive the policy changes required.",
]

ROUTING_SET = [(p, "Economy") for p in ECONOMY] + [(p, "Workhorse") for p in WORKHORSE] + [(p, "Premium") for p in PREMIUM]
