"""Ten golden cases per blueprint. Each case has an input, an optional resume answer, and expectations the harness checks."""

GOLDEN: dict[str, list[dict]] = {
    "doc-reconciliation": [
        {"input": {"tolerance_pct": 2}, "resume": {"decision": "approve", "notes": "ok"}, "expect": {"status": "completed", "review_required": True, "anomaly_codes": ["over_tolerance", "missing_po", "duplicate_invoice_number", "terms_mismatch", "date_before_po", "unknown_vendor"], "escalated_min": 6}},
        {"input": {"tolerance_pct": 2, "auto_approve": True}, "expect": {"status": "completed", "review_required": False, "escalated_min": 6}},
        {"input": {"invoice_numbers": ["INV-9002"]}, "resume": {"decision": "reject"}, "expect": {"anomaly_codes": ["over_tolerance"], "escalated_min": 1}},
        {"input": {"invoice_numbers": ["INV-9002"], "tolerance_pct": 15}, "expect": {"review_required": False, "anomalies_max": 0}},
        {"input": {"invoice_numbers": ["INV-9005"]}, "resume": {"decision": "approve_with_notes", "notes": "PO created after the fact"}, "expect": {"anomaly_codes": ["missing_po"]}},
        {"input": {"invoice_numbers": ["INV-9003", "INV-9003"]}, "resume": "approve", "expect": {"anomaly_codes": ["duplicate_invoice_number"]}},
        {"input": {"invoice_numbers": ["INV-9009"]}, "resume": "approve", "expect": {"anomaly_codes": ["terms_mismatch"]}},
        {"input": {"invoice_numbers": ["INV-9012"]}, "resume": "approve", "expect": {"anomaly_codes": ["date_before_po"]}},
        {"input": {"invoice_numbers": ["INV-9015"]}, "resume": "approve", "expect": {"anomaly_codes": ["unknown_vendor"]}},
        {"input": {"invoice_numbers": ["INV-9000", "INV-9001"]}, "expect": {"review_required": False, "anomalies_max": 0, "output_has": ["summary_md"]}},
    ],
    "sage-lens": [
        {"input": {"question": "What does Tesla sell and where does it build vehicles?"}, "expect": {"status": "completed", "review_required": False, "sources_min": 3, "output_eq": {"company": "Tesla"}}},
        {"input": {"question": "Give me an overview"}, "resume": {"decision": "Apple"}, "expect": {"review_required": True, "output_eq": {"company": "Apple"}, "sources_min": 3}},
        {"input": {"question": "hi"}, "resume": "Microsoft", "expect": {"review_required": True, "output_eq": {"company": "Microsoft"}}},
        {"input": {"question": "How does Microsoft sell AI models to enterprises?"}, "expect": {"output_eq": {"company": "Microsoft"}, "output_has": ["answer_md", "confidence"]}},
        {"input": {"question": "Where are Anthropic's Claude models available?"}, "expect": {"output_eq": {"company": "Anthropic"}, "sources_min": 3}},
        {"input": {"question": "Apple services revenue"}, "expect": {"output_eq": {"company": "Apple"}, "attempts_max": 3}},
        {"input": {"question": "Tell me about Tesla energy storage"}, "expect": {"output_eq": {"company": "Tesla"}}},
        {"input": {"question": "Summarize Anthropic's responsible scaling policy"}, "expect": {"output_eq": {"company": "Anthropic"}, "output_has": ["sources"]}},
        {"input": {"question": "Compare", "company": "Microsoft"}, "expect": {"review_required": False, "output_eq": {"company": "Microsoft"}}},
        {"input": {"question": "What is Apple's supply chain strategy in India?"}, "expect": {"output_eq": {"company": "Apple"}, "attempts_max": 3}},
    ],
    "learning-path": [
        {"input": {"function": "Finance", "role": "Analyst", "competency": "SQL"}, "expect": {"status": "completed", "levels": 3, "reference_contains": "mode.com"}},
        {"input": {"function": "Engineering", "role": "Solutions architect", "competency": "Agentic AI"}, "expect": {"levels": 3, "reference_contains": "langchain"}},
        {"input": {"function": "HR", "role": "Business partner", "competency": "Prompt engineering"}, "expect": {"levels": 3, "reference_contains": "prompt-engineering"}},
        {"input": {"function": "Legal", "role": "Counsel", "competency": "Data privacy"}, "expect": {"levels": 3, "reference_contains": "europa.eu"}},
        {"input": {"function": "Finance", "role": "Controller", "competency": "Financial analysis"}, "expect": {"levels": 3, "reference_contains": "corporatefinanceinstitute"}},
        {"input": {"function": "Sales", "role": "Account executive", "competency": "Negotiation"}, "expect": {"levels": 3, "reference_contains": "google.com/search"}},
        {"input": {"function": "Operations", "role": "Planner", "competency": "sql"}, "expect": {"reference_contains": "postgresql"}},
        {"input": {"function": "IT", "role": "Engineer", "competency": "Agentic AI"}, "expect": {"output_has": ["path_md", "critique"]}},
        {"input": {"function": "Marketing", "role": "Manager", "competency": "Prompt engineering"}, "expect": {"levels": 3}},
        {"input": {"function": "Finance", "role": "Analyst", "competency": "Data privacy"}, "expect": {"levels": 3, "output_has": ["references"]}},
    ],
    "review-panel": [
        {"input": {"draft_id": "DRAFT-1"}, "resume": {"decision": "revise", "notes": "respect contract terms"}, "expect": {"status": "completed", "review_required": True, "blockers_min": 1, "output_eq": {"verdict": "revise"}}},
        {"input": {"draft_id": "DRAFT-2"}, "resume": "reject", "expect": {"review_required": True, "blockers_min": 1, "output_eq": {"verdict": "reject"}}},
        {"input": {"draft_id": "DRAFT-3"}, "expect": {"review_required": False, "output_eq": {"verdict": "approved"}}},
        {"input": {"text": "We will pay net 90 regardless of contract terms."}, "resume": "approve", "expect": {"review_required": True, "output_eq": {"verdict": "approve"}}},
        {"input": {"text": "The quarterly newsletter goes out on Friday. Please send items to comms by Wednesday noon. Thank you."}, "expect": {"review_required": False}},
        {"input": {"text": "Use any data you like with the new tool, there are no limits."}, "resume": "reject", "expect": {"blockers_min": 1}},
        {"input": {"text": "Short."}, "expect": {"review_required": False, "output_has": ["critics"]}},
        {"input": {"draft_id": "DRAFT-3", "title": "Update"}, "expect": {"output_eq": {"title": "Quarterly training update"}}},
        {"input": {"text": "Customer records may be uploaded to any AI tool at our discretion."}, "resume": {"decision": "revise", "notes": ""}, "expect": {"blockers_min": 2}},
        {"input": {"draft_id": "DRAFT-1"}, "resume": "approve", "expect": {"output_eq": {"verdict": "approve"}, "output_has": ["revised_md"]}},
    ],
    "data-analyst": [
        {"input": {"question": "What is the total revenue by region?"}, "expect": {"status": "completed", "output_eq": {"route": "stats", "dimension": "region", "metric": "revenue"}, "table_rows": 4}},
        {"input": {"question": "Plot monthly revenue over time"}, "expect": {"output_eq": {"route": "chart", "dimension": "month"}, "table_rows": 12, "chart": True}},
        {"input": {"question": "Which products sold the most units?"}, "expect": {"output_eq": {"route": "stats", "dimension": "product", "metric": "units"}, "table_rows": 8}},
        {"input": {"question": "Show me revenue per product"}, "expect": {"output_eq": {"route": "query", "dimension": "product"}}},
        {"input": {"question": "Average units by region"}, "expect": {"output_eq": {"route": "stats", "metric": "units", "dimension": "region"}}},
        {"input": {"question": "Chart units by product"}, "expect": {"output_eq": {"route": "chart", "dimension": "product", "metric": "units"}, "chart": True}},
        {"input": {"question": "Revenue trend"}, "expect": {"output_eq": {"route": "chart", "dimension": "month"}}},
        {"input": {"question": "Top region"}, "expect": {"output_eq": {"route": "stats", "dimension": "region"}}},
        {"input": {"question": "Sum of revenue"}, "expect": {"output_eq": {"route": "stats"}, "output_has": ["total", "narrative_md"]}},
        {"input": {"question": "List regions"}, "expect": {"output_eq": {"route": "query", "dimension": "region"}, "table_rows": 4}},
    ],
    "knowledge-qa": [
        {"input": {"question": "What is the hotel limit per night when travelling?"}, "expect": {"status": "completed", "top_retrieved": "POL-001", "output_eq": {"grounded": True}}},
        {"input": {"question": "What do I need for a purchase over 50,000 USD?"}, "expect": {"top_retrieved": "POL-002"}},
        {"input": {"question": "Can I paste payroll data into an external AI tool?"}, "expect": {"top_retrieved": "POL-005"}},
        {"input": {"question": "How many days can I work remotely each week?"}, "expect": {"top_retrieved": "POL-004"}},
        {"input": {"question": "What tolerance is accepted in invoice matching?"}, "expect": {"top_retrieved": "POL-003"}},
        {"input": {"question": "What is my annual learning budget?"}, "expect": {"top_retrieved": "POL-008"}},
        {"input": {"question": "When do contracts need legal review?"}, "expect": {"top_retrieved": "POL-009"}},
        {"input": {"question": "How fast must I report phishing?"}, "expect": {"top_retrieved": "POL-010"}},
        {"input": {"question": "Documents needed for vendor onboarding"}, "expect": {"top_retrieved": "POL-007"}},
        {"input": {"question": "Is every AI request metered?"}, "expect": {"top_retrieved": "POL-006", "output_has": ["citations"]}},
    ],
}
