"""Framework flavors: render a blueprint manifest into a runnable starter project for each major agent SDK.

API shapes follow the official quickstarts as of September 2026 (see the frameworks page for links).
"""

from __future__ import annotations

import io
import json
import zipfile

FRAMEWORKS: dict[str, dict] = {
    "openai-agents": {"name": "OpenAI Agents SDK", "install": "pip install openai-agents openai", "docs": "https://openai.github.io/openai-agents-python/", "license": "MIT", "hosted": "Agent Builder (deprecated Nov 30, 2026); self-host", "language": "Python"},
    "langgraph": {"name": "LangGraph", "install": "pip install -U langgraph langchain langchain-openai", "docs": "https://docs.langchain.com/oss/python/langgraph/overview", "license": "MIT", "hosted": "LangSmith Deployment, from $39 per seat per month plus compute", "language": "Python"},
    "crewai": {"name": "CrewAI", "install": "pip install crewai", "docs": "https://docs.crewai.com/en/quickstart", "license": "MIT", "hosted": "CrewAI AMP, free tier of 50 executions per month", "language": "Python"},
    "agent-framework": {"name": "Microsoft Agent Framework", "install": "pip install agent-framework", "docs": "https://learn.microsoft.com/en-us/agent-framework/overview", "license": "MIT", "hosted": "Foundry Hosted Agents via azd", "language": "Python"},
    "adk": {"name": "Google ADK", "install": "pip install google-adk litellm", "docs": "https://adk.dev/get-started/python/", "license": "Apache-2.0", "hosted": "Agent Runtime on Gemini Enterprise Agent Platform", "language": "Python"},
}


def _slug(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s.lower()).strip("_")


def _tools(manifest: dict) -> list[dict]:
    """Deterministic nodes become tool stubs; the model node becomes the agent."""
    return [n for n in manifest["graph"]["nodes"] if n["kind"] in ("tool", "gate")]


def _readme(manifest: dict, fw: dict, key: str) -> str:
    return f"""# {manifest['name']} as {fw['name']}

Generated by the Enterprise AI Playground from the `{manifest['id']}` blueprint.

Pattern: {manifest['pattern']}
{manifest['description']}

## Run through the playground gateway (recommended)

```bash
{fw['install']}
export PLAYGROUND_BASE_URL=http://localhost:8000/openai/v1   # your playground's API address
export PLAYGROUND_TOKEN=pgk_...                              # Admin → Settings → Personal tokens
export PLAYGROUND_MODEL=smart                                # or any catalog id, e.g. claude-sonnet-5
python agent.py
python -m pytest -q
```

The gateway speaks the OpenAI Chat Completions API, so this project needs no provider key of its own: the playground
applies your role policy, budget, Smart routing and personal or platform keys, and every call lands in your ledger and
traces. To talk to a provider directly instead, point `PLAYGROUND_BASE_URL` at the provider's OpenAI-compatible endpoint
and use its key as `PLAYGROUND_TOKEN`.

## What is generated

- `agent.py`: the agent with one tool stub per deterministic step ({', '.join(t['label'] for t in _tools(manifest))}).
- `sample_input.json`: the first sample input from the playground.
- `test_smoke.py`: an offline test that checks the module imports and the tool stubs are wired.

Docs: {fw['docs']} · Hosted runtime: {fw['hosted']} · License of the framework: {fw['license']}
"""


def _tool_stubs(manifest: dict, decorator: str) -> str:
    out = []
    for t in _tools(manifest):
        fn = _slug(t["id"])
        out.append(f'''{decorator}
def {fn}(payload: str) -> str:
    """{t['label']}: replace this stub with the deterministic logic from the playground blueprint."""
    return f"{t['label']} done for: {{payload[:60]}}"
''')
    return "\n".join(out)


from app.flavors_renderers import RENDERERS


def render_project(manifest: dict, framework: str) -> dict[str, str]:
    if framework not in RENDERERS:
        raise KeyError(framework)
    fw = FRAMEWORKS[framework]
    files = RENDERERS[framework](manifest)
    tool_names = [_slug(t["id"]) for t in _tools(manifest)]
    files["README.md"] = _readme(manifest, fw, framework)
    _attach_extras(files, manifest)
    files["sample_input.json"] = json.dumps((manifest.get("samples") or [{"input": {}}])[0]["input"], indent=2)
    files["requirements.txt"] = fw["install"].replace("pip install ", "").replace(" ", "\n").replace("'", "") + "\npytest\n"
    files["test_smoke.py"] = f'''"""Offline smoke test: the module parses and every deterministic step has a stub. No network, no keys."""
import ast
from pathlib import Path

TOOLS = {tool_names!r}


def test_agent_module_parses_and_has_tool_stubs():
    tree = ast.parse(Path(__file__).with_name("agent.py").read_text())
    names = {{n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}}
    for tool in TOOLS:
        assert tool in names, tool


def test_sample_input_is_json():
    import json
    json.loads(Path(__file__).with_name("sample_input.json").read_text())
'''
    return files


def _attach_extras(files: dict[str, str], manifest: dict) -> None:
    """Skills ship as SKILL.md files; connectors ship as an mcp.json the SDKs' MCP clients can load."""
    from app.skills import get_skill

    for sid in manifest.get("skills") or []:
        s = get_skill(sid)
        if s:
            files[f"skills/{sid}/SKILL.md"] = f"---\nname: {sid}\ndescription: {s['description']}\nsource: {s['source']['url']}\nlicense: {s['source']['license']}\n---\n\n{s['body']}"
    connectors = manifest.get("connectors") or []
    if connectors:
        from app.db import SessionLocal
        from app.models import Connector

        servers = {}
        with SessionLocal() as db:
            for cid in connectors:
                c = db.get(Connector, cid)
                if c is not None:
                    from app.connectors import install_snippet

                    servers.update(install_snippet(c))
        files["mcp.json"] = json.dumps({"mcpServers": servers}, indent=2)


def zip_project(files: dict[str, str], root: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in files.items():
            zf.writestr(f"{root}/{name}", content)
    return buf.getvalue()
