"""Framework flavors: render a blueprint manifest into a runnable starter project for each major agent SDK.

API shapes follow the official quickstarts as of September 2026 (see the frameworks page for links).
"""

from __future__ import annotations

import io
import json
import zipfile

FRAMEWORKS: dict[str, dict] = {
    "openai-agents": {"name": "OpenAI Agents SDK", "install": "pip install openai-agents 'openai-agents[litellm]'", "docs": "https://openai.github.io/openai-agents-python/", "license": "MIT", "hosted": "Agent Builder (deprecated Nov 30, 2026); self-host", "language": "Python"},
    "langgraph": {"name": "LangGraph", "install": "pip install -U langgraph langchain langchain-anthropic", "docs": "https://docs.langchain.com/oss/python/langgraph/overview", "license": "MIT", "hosted": "LangSmith Deployment, from $39 per seat per month plus compute", "language": "Python"},
    "crewai": {"name": "CrewAI", "install": "pip install crewai", "docs": "https://docs.crewai.com/en/quickstart", "license": "MIT", "hosted": "CrewAI AMP, free tier of 50 executions per month", "language": "Python"},
    "agent-framework": {"name": "Microsoft Agent Framework", "install": "pip install agent-framework", "docs": "https://learn.microsoft.com/en-us/agent-framework/overview", "license": "MIT", "hosted": "Foundry Hosted Agents via azd", "language": "Python"},
    "adk": {"name": "Google ADK", "install": "pip install google-adk litellm", "docs": "https://adk.dev/get-started/python/", "license": "Apache-2.0", "hosted": "Agent Runtime on Gemini Enterprise Agent Platform", "language": "Python"},
}


def _slug(s: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in s.lower()).strip("_")


def _tools(manifest: dict) -> list[dict]:
    """Deterministic nodes become tool stubs; the model node becomes the agent."""
    return [n for n in manifest["graph"]["nodes"] if n["kind"] in ("tool", "gate")]


def _readme(manifest: dict, fw: dict, key: str) -> str:
    return f"""# {manifest['name']} as {fw['name']}

Generated by the Enterprise AI Playground from the `{manifest['id']}` blueprint.

Pattern: {manifest['pattern']}
{manifest['description']}

## Run

```bash
{fw['install']}
export ANTHROPIC_API_KEY=...   # or the provider your policy allows
python agent.py
python -m pytest -q
```

## What is generated

- `agent.py`: the agent with one tool stub per deterministic step ({', '.join(t['label'] for t in _tools(manifest))}).
- `sample_input.json`: the first sample input from the playground.
- `test_smoke.py`: an offline test that checks the module imports and the tool stubs are wired.

Docs: {fw['docs']} · Hosted runtime: {fw['hosted']} · License of the framework: {fw['license']}
"""


def _tool_stubs(manifest: dict, decorator: str) -> str:
    out = []
    for t in _tools(manifest):
        fn = _slug(t["id"])
        out.append(f'''{decorator}
def {fn}(payload: str) -> str:
    """{t['label']}: replace this stub with the deterministic logic from the playground blueprint."""
    return f"{t['label']} done for: {{payload[:60]}}"
''')
    return "\n".join(out)


def render_openai_agents(m: dict) -> dict[str, str]:
    tools = ", ".join(_slug(t["id"]) for t in _tools(m))
    agent = f'''"""{m['name']} on the OpenAI Agents SDK. Model via LiteLLM so any playground provider works."""
import json
from agents import Agent, Runner
from agents.decorators import tool
from agents.extensions.models.litellm_model import LitellmModel

{_tool_stubs(m, "@tool")}

agent = Agent(
    name="{m['name']}",
    instructions="""{m['description']}""",
    model=LitellmModel(model="anthropic/claude-sonnet-5"),
    tools=[{tools}],
)

if __name__ == "__main__":
    sample = json.load(open("sample_input.json"))
    result = Runner.run_sync(agent, json.dumps(sample))
    print(result.final_output)
'''
    return {"agent.py": agent}


def render_langgraph(m: dict) -> dict[str, str]:
    tools = ", ".join(_slug(t["id"]) for t in _tools(m))
    agent = f'''"""{m['name']} on LangGraph via create_agent. Swap the model string for any provider you are allowed to use."""
import json
from langchain.agents import create_agent

{_tool_stubs(m, "")}

agent = create_agent(
    model="anthropic:claude-sonnet-5",
    tools=[{tools}],
    system_prompt="""{m['description']}""",
)

if __name__ == "__main__":
    sample = json.load(open("sample_input.json"))
    result = agent.invoke({{"messages": [{{"role": "user", "content": json.dumps(sample)}}]}})
    print(result["messages"][-1].content_blocks)
'''
    return {"agent.py": agent}


def render_crewai(m: dict) -> dict[str, str]:
    tools = ", ".join(_slug(t["id"]) for t in _tools(m))
    stubs = "\n".join(f'''@tool("{t['label']}")
def {_slug(t['id'])}(payload: str) -> str:
    """{t['label']}: replace this stub with the deterministic logic from the playground blueprint."""
    return f"{t['label']} done for: {{payload[:60]}}"
''' for t in _tools(m))
    agent = f'''"""{m['name']} as a CrewAI crew."""
import json
from crewai import Agent, Crew, Process, Task
from crewai.tools import tool

{stubs}

worker = Agent(role="{m['name']}", goal="{m['summary']}", backstory="""{m['description']}""", tools=[{tools}], llm="anthropic/claude-sonnet-5")
task = Task(description="Handle the input: {{payload}}", expected_output="A markdown report", agent=worker)
crew = Crew(agents=[worker], tasks=[task], process=Process.sequential)

if __name__ == "__main__":
    sample = json.load(open("sample_input.json"))
    print(crew.kickoff(inputs={{"payload": json.dumps(sample)}}))
'''
    return {"agent.py": agent}


def render_agent_framework(m: dict) -> dict[str, str]:
    tools = ", ".join(_slug(t["id"]) for t in _tools(m))
    agent = f'''"""{m['name']} on Microsoft Agent Framework (Python)."""
import asyncio
import json
from agent_framework import Agent, tool
from agent_framework.openai import OpenAIChatClient

{_tool_stubs(m, '@tool(approval_mode="never_require")')}

agent = Agent(client=OpenAIChatClient(), name="{_slug(m['name'])}", instructions="""{m['description']}""", tools=[{tools}])

if __name__ == "__main__":
    sample = json.load(open("sample_input.json"))
    print(asyncio.run(agent.run(json.dumps(sample))).text)
'''
    return {"agent.py": agent}


def render_adk(m: dict) -> dict[str, str]:
    tools = ", ".join(_slug(t["id"]) for t in _tools(m))
    agent = f'''"""{m['name']} on Google ADK. Run with `adk run .` or `adk web`."""
from google.adk.agents.llm_agent import Agent
from google.adk.models.lite_llm import LiteLlm

{_tool_stubs(m, "")}

root_agent = Agent(
    model=LiteLlm(model="anthropic/claude-sonnet-5"),
    name="{_slug(m['name'])}",
    description="{m['summary']}",
    instruction="""{m['description']}""",
    tools=[{tools}],
)
'''
    init = "try:\n    from . import agent  # noqa: F401\nexcept ImportError:  # google-adk not installed yet; run pip install -r requirements.txt\n    pass\n"
    return {"agent.py": agent, "__init__.py": init}


RENDERERS = {"openai-agents": render_openai_agents, "langgraph": render_langgraph, "crewai": render_crewai, "agent-framework": render_agent_framework, "adk": render_adk}


def render_project(manifest: dict, framework: str) -> dict[str, str]:
    if framework not in RENDERERS:
        raise KeyError(framework)
    fw = FRAMEWORKS[framework]
    files = RENDERERS[framework](manifest)
    tool_names = [_slug(t["id"]) for t in _tools(manifest)]
    files["README.md"] = _readme(manifest, fw, framework)
    _attach_extras(files, manifest)
    files["sample_input.json"] = json.dumps((manifest.get("samples") or [{"input": {}}])[0]["input"], indent=2)
    files["requirements.txt"] = fw["install"].replace("pip install ", "").replace(" ", "\n").replace("'", "") + "\npytest\n"
    files["test_smoke.py"] = f'''"""Offline smoke test: the module parses and every deterministic step has a stub. No network, no keys."""
import ast
from pathlib import Path

TOOLS = {tool_names!r}


def test_agent_module_parses_and_has_tool_stubs():
    tree = ast.parse(Path(__file__).with_name("agent.py").read_text())
    names = {{n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}}
    for tool in TOOLS:
        assert tool in names, tool


def test_sample_input_is_json():
    import json
    json.loads(Path(__file__).with_name("sample_input.json").read_text())
'''
    return files


def _attach_extras(files: dict[str, str], manifest: dict) -> None:
    """Skills ship as SKILL.md files; connectors ship as an mcp.json the SDKs' MCP clients can load."""
    from app.skills import get_skill

    for sid in manifest.get("skills") or []:
        s = get_skill(sid)
        if s:
            files[f"skills/{sid}/SKILL.md"] = f"---\nname: {sid}\ndescription: {s['description']}\nsource: {s['source']['url']}\nlicense: {s['source']['license']}\n---\n\n{s['body']}"
    connectors = manifest.get("connectors") or []
    if connectors:
        from app.db import SessionLocal
        from app.models import Connector

        servers = {}
        with SessionLocal() as db:
            for cid in connectors:
                c = db.get(Connector, cid)
                if c is not None:
                    from app.connectors import install_snippet

                    servers.update(install_snippet(c))
        files["mcp.json"] = json.dumps({"mcpServers": servers}, indent=2)


def zip_project(files: dict[str, str], root: str) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for name, content in files.items():
            zf.writestr(f"{root}/{name}", content)
    return buf.getvalue()
